### ISSUE TITLE
Automatically detect --gcp-project from gcloud for list and get-status commands

### ISSUE THREAD

**Issue by ahmetb** [GoogleCloudPlatform/k8s-multicluster-ingress#162]
low-pri; not beta blocker.

1. Consider inferring gcp project from `gcloud config get-value core/project`. Most other tools built on gcloud does this (while still providing a --flag to customize).

2. Consider renaming --gcp-project to --project  unless there's plans to support other cloud providers. This makes it consistent across other GCP tools, like gcloud.

**Comment by nikhiljindal** [comment]
Yes we auto infer gcp-project from gcloud: https://github.com/GoogleCloudPlatform/k8s-multicluster-ingress/issues/80.

But turns out that we did it only for `kubemci create` and `kubemci delete`.
We need to do it for `kubemci list` and `kubemci get-status` as well.

cc @G-Harmon You can take this up since you are planning to add missing `TestValidateGetStatusWithGCPProject` and `TestValidateListWithGCPProject` tests.

We do not plan to rename gcp-project at this time.

**Comment by ahmetb** [comment]
Got it.

Once we add it to list/get-status, I strongly recommend removing it from the tutorials.

**Comment by G-Harmon** [comment]
Fixed with #172 and #176.
